FROM nginx:latest

RUN apt-get update && apt-get install -y git curl apt-transport-https gnupg2 

RUN curl -sL https://deb.nodesource.com/setup_9.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y nodejs yarn
RUN git clone https://github.com/osallou/goswift.git /root/goswift
RUN cd /root/goswift/goswift-ui-web && yarn install

ADD nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /root/goswift/goswift-ui-web
ENV GOSWIFT_WEB_ROOT="/root/goswift/goswift-ui-web"
ENTRYPOINT ["/root/goswift/docker/startweb.sh"]
