FROM nginx

RUN apt-get update && apt-get install -y git npm curl apt-transport-https

RUN git clone https://github.com/osallou/goswift.git /root/goswift
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install -y nodejs yarn
RUN cd /root/goswift/goswift-ui-web && yarn install

WORKDIR /root/goswift/goswift-ui-web
ENV GOSWIFT_WEB_ROOT="/root/goswift/goswift-ui-web"
ENTRYPOINT ["/root/goswift/goswift-ui-web/scripts/startweb.sh"]
