FROM python:3

MAINTAINER Olivier Sallou <olivier.sallou@irisa.fr>

RUN apt-get update && apt-get install -y python3-pip

RUN git clone https://github.com/osallou/goswift.git /root/goswift
RUN cd /root/goswift && pip3 install -r requirements.txt \
     && pip3 install gunicorn && python3 setup.py install

# Should be overriden at runtime by a real config file
RUN cd /root/goswift && cp config.yml.example config.yml

WORKDIR /root/goswift
EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0", "goswift.app:app"]
